In [ ]:
#1.Write a python program to find the largest of 3 numbers

num1 = 10
num2 = 20
num3 = 30

if (num1 >= num2) and (num1 >= num3):
   largest = num1
elif (num2 >= num1) and (num2 >= num3):
   largest = num2
else:
   largest = num3

print("The largest number is", largest)

The largest number is 30

In [3]:
# 2.Write a python program to find the numbers divisible by 3 and 7 from 100 to 800
for x in range(100, 800):
    if (x%3==0) and (x%7==0):
        print (x)

105
126
147
168
189
210
231
252
273
294
315
336
357
378
399
420
441
462
483
504
525
546
567
588
609
630
651
672
693
714
735
756
777
798

In [ ]:
#3.Write a python program to find the count of numbers divisible by 8 from 1 to 1000
lower, upper = 1, 1000
count = 0

for num in range(lower, upper + 1):
    if num%8 == 0:
        count += 1

print(count)

125

In [ ]:
# 4.#Write a Python program to construct the following pattern, using anested for loop.

n = 9
for i in range(1,n+1):
    if i <= 5:
        for j in range(0, i):
            print('*', end="")
    else:
        for k in range(0, n-i+1):
            print('*', end="")
    print('')

*
**
***
****
*****
****
***
**
*

In [ ]:
# 5. Write a Python program to reverse a list using a for loop.
#Sample input: 10,40,30,70
#Sample output: 70,30,40,10
list1 = [10,40,30,70]
print("List before reverse : ",list1)
list1.reverse()
print("List after reverse : ",list1)

List before reverse :  [10, 40, 30, 70]
List after reverse :  [70, 30, 40, 10]

In [ ]:
# 6. Write a python program to print the multiplication table of 1-10

for x in range(1, 11):
    print(" \n\n Multiplication table of " ,x )
    for y in range(1, 11):
        print(x, "*", y,"=", (x*y))

 Multiplication table of  1
1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
1 * 10 = 10


 Multiplication table of  2
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20


 Multiplication table of  3
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
3 * 10 = 30


 Multiplication table of  4
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
4 * 10 = 40


 Multiplication table of  5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


 Multiplication table of  6
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
6 * 10 = 60


 Multiplication table of  7
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
7 * 10 = 70


 Multiplication table of  8
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
8 * 10 = 80


 Multiplication table of  9
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
9 * 10 = 90


 Multiplication table of  10
10 * 1 = 10
10 * 2 = 20
10 * 3 = 30
10 * 4 = 40
10 * 5 = 50
10 * 6 = 60
10 * 7 = 70
10 * 8 = 80
10 * 9 = 90
10 * 10 = 100

In [4]:
# 7.Write a python program to find the sum of integers less than 25 using while loop
n= 25
if n < 0:
   print("number")
else:
   sum = 0
   while(n > 0):
       sum += n
       n -= 1
   print( sum)

325

In [ ]:
# 8.Write a python program to print the even numbers in a list of numbers

list1 = [1,2,3,4,5,6,7,8,9,10] 
for num in list1:
    if num % 2 == 0:
        print(num, end=" ")

2 4 6 8 10

In [ ]:
# 9. write a python program to find the sum of elements in a number list

list1 = [1,2,3,4,5,6,7,8,9,10] 
total=0
for i in range(0, len(list1)):
    total = total + list1[i]
print("Sum", total)

Sum 55

In [ ]:
# 10. Write a Python program to check whether a number is prime or not.
x = 3
if x > 1:
    for i in range(2, int(x/2)+1):
        if (x % i) == 0:
            print(x, "is not a prime")
        break
    else:
        print(x, "is a prime")
else:
    print(x, "is not a prime")

3 is a prime